// <auto-generated />
namespace MinhLam.Social.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPrivacyFlagTypeToProfileAttributeTypeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPrivacyFlagTypeToProfileAttributeTypeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202109091315145_AddPrivacyFlagTypeToProfileAttributeTypeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
