// <auto-generated />
namespace MinhLam.Social.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UpdateForeignKeyPrivacyFlagTypeIdAttributeTypeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateForeignKeyPrivacyFlagTypeIdAttributeTypeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202109091318190_UpdateForeignKeyPrivacyFlagTypeIdAttributeTypeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
